# Generated by Django 4.2.6 on 2024-01-27 12:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0036_card_comment"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="board",
        #     name="backgroundimage",
        # ),
        migrations.RemoveField(
            model_name="meeting",
            name="member",
        ),
        # migrations.AlterField(
        #     model_name="board",
        #     name="invitation_link",
        #     field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        # ),
        migrations.CreateModel(
            name="MemberMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mmeet",
                        to="tascrum.meeting",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mmember",
                        to="tascrum.member",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="meeting",
            name="members",
            field=models.ManyToManyField(
                related_name="mmembers",
                through="tascrum.MemberMeeting",
                to="tascrum.member",
            ),
        ),
    ]
