# Generated by Django 4.2.6 on 2024-01-29 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tascrum', '0036_card_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='backgroundImage',
        ),
        migrations.AlterField(
            model_name='board',
            name='invitation_link',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
