# Generated by Django 4.2.6 on 2024-01-27 16:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tascrum', '0037_remove_board_backgroundimage_remove_meeting_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='backgroundimage',
        ),
        # migrations.AlterField(
        #     model_name='board',
        #     name='invitation_link',
        #     field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        # ),
    ]
