# Generated by Django 4.2.6 on 2024-01-27 19:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0038_remove_board_backgroundimage_and_more"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="board",
        #     name="backgroundimage",
        # ),
        # migrations.AlterField(
        #     model_name="board",
        #     name="invitation_link",
        #     field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        # ),
        migrations.RemoveField(
            model_name="meeting",
            name="members",
        ),
        migrations.DeleteModel(
            name="MemberMeeting",
        ),
        # migrations.AddField(
        #     model_name="board",
        #     name="backgroundimage",
        #     field=models.ImageField(default="default_profile.png", upload_to="images/"),
        # ),
        migrations.AddField(
            model_name="meeting",
            name="members",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mmember",
                to="tascrum.member",
            ),
            preserve_default=False,
        ),
    ]
